
package cl.blueprintsit.ws.pipesponsor;

import java.io.FileInputStream;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SponsorModuleService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://mlfpcdesbo.alico.corp:8080/SrpSrv/SponsorModuleService.svc?wsdl")
public class SponsorModuleService
    extends Service
{

    private final static URL SPONSORMODULESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.blueprintsit.ws.pipesponsor.SponsorModuleService.class.getName());

    static {
        Properties prop = new Properties();
        InputStream input = null;
        String urlString="";
        try {
            input = new FileInputStream("config.properties");
            // load a properties file
            prop.load(input);
            urlString=prop.getProperty("WsSponsor");
            System.out.println("SponsorModuleService WsSponsor="+urlString);
        } catch(Exception e){
            System.out.println("SponsorModuleService.static No se encuentra configurado el servicio WsSponsor");
        }
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.blueprintsit.ws.pipesponsor.SponsorModuleService.class.getResource(".");
            //url = new URL(baseUrl, "http://mlfpcdesbo.alico.corp:8080/SrpSrv/SponsorModuleService.svc?wsdl");
            url = new URL(baseUrl, urlString+"?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '"+urlString+"?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SPONSORMODULESERVICE_WSDL_LOCATION = url;
    }

    public SponsorModuleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SponsorModuleService() {
        super(SPONSORMODULESERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "SponsorModuleService"));
    }

    /**
     * 
     * @return
     *     returns ISponsorMouleService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISponsorMouleService")
    public ISponsorMouleService getBasicHttpBindingISponsorMouleService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISponsorMouleService"), ISponsorMouleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISponsorMouleService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISponsorMouleService")
    public ISponsorMouleService getBasicHttpBindingISponsorMouleService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISponsorMouleService"), ISponsorMouleService.class, features);
    }

}
