
package cl.blueprintsit.ws.bulkPreingreso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WsBulkSoap", targetNamespace = "http://preingreso.metlife.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsBulkSoap {


    /**
     * 
     * @param fechaRecepcion
     * @param nombreAdjunto
     * @param tipoMovimiento
     * @param sesionId
     * @return
     *     returns cl.blueprintsit.ws.bulkPreingreso.BulkBo
     */
    @WebMethod(operationName = "Crear", action = "http://preingreso.metlife.cl/Crear")
    @WebResult(name = "CrearResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "Crear", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.Crear")
    @ResponseWrapper(localName = "CrearResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.CrearResponse")
    public BulkBo crear(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "tipoMovimiento", targetNamespace = "http://preingreso.metlife.cl/")
        int tipoMovimiento,
        @WebParam(name = "nombreAdjunto", targetNamespace = "http://preingreso.metlife.cl/")
        String nombreAdjunto,
        @WebParam(name = "fechaRecepcion", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaRecepcion);

    /**
     * 
     * @param movto
     * @param sesionId
     * @return
     *     returns cl.blueprintsit.ws.bulkPreingreso.ErrorBo
     */
    @WebMethod(operationName = "CrearAlta", action = "http://preingreso.metlife.cl/CrearAlta")
    @WebResult(name = "CrearAltaResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "CrearAlta", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.CrearAlta")
    @ResponseWrapper(localName = "CrearAltaResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.CrearAltaResponse")
    public ErrorBo crearAlta(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "movto", targetNamespace = "http://preingreso.metlife.cl/")
        MovtoAltaBo movto);

    /**
     * 
     * @param movto
     * @param sesionId
     * @return
     *     returns cl.blueprintsit.ws.bulkPreingreso.ErrorBo
     */
    @WebMethod(operationName = "CrearBaja", action = "http://preingreso.metlife.cl/CrearBaja")
    @WebResult(name = "CrearBajaResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "CrearBaja", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.CrearBaja")
    @ResponseWrapper(localName = "CrearBajaResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.CrearBajaResponse")
    public ErrorBo crearBaja(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "movto", targetNamespace = "http://preingreso.metlife.cl/")
        MovtoBajaBo movto);

    /**
     * 
     * @param sesionId
     * @param bulkId
     * @return
     *     returns cl.blueprintsit.ws.bulkPreingreso.ErrorBo
     */
    @WebMethod(operationName = "Ejecutar", action = "http://preingreso.metlife.cl/Ejecutar")
    @WebResult(name = "EjecutarResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "Ejecutar", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.Ejecutar")
    @ResponseWrapper(localName = "EjecutarResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.EjecutarResponse")
    public ErrorBo ejecutar(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId);

    /**
     * 
     * @param sesionId
     * @param bulkId
     * @return
     *     returns cl.blueprintsit.ws.bulkPreingreso.BulkBo
     */
    @WebMethod(operationName = "Info", action = "http://preingreso.metlife.cl/Info")
    @WebResult(name = "InfoResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "Info", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.Info")
    @ResponseWrapper(localName = "InfoResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.InfoResponse")
    public BulkBo info(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId);

    /**
     * 
     * @param sesionId
     * @param bulkId
     * @return
     *     returns cl.blueprintsit.ws.bulkPreingreso.ArrayOfMovtoErrorBo
     */
    @WebMethod(operationName = "ListarError", action = "http://preingreso.metlife.cl/ListarError")
    @WebResult(name = "ListarErrorResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "ListarError", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.ListarError")
    @ResponseWrapper(localName = "ListarErrorResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.ListarErrorResponse")
    public ArrayOfMovtoErrorBo listarError(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId);

    /**
     * 
     * @param sesionId
     * @param bulkId
     * @return
     *     returns cl.blueprintsit.ws.bulkPreingreso.ArrayOfSetBo
     */
    @WebMethod(operationName = "ListarSet", action = "http://preingreso.metlife.cl/ListarSet")
    @WebResult(name = "ListarSetResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "ListarSet", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.ListarSet")
    @ResponseWrapper(localName = "ListarSetResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.ListarSetResponse")
    public ArrayOfSetBo listarSet(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId);

    /**
     * 
     * @param fechaDesde
     * @param lote
     * @param corredorRutDv
     * @param sesionId
     * @param fechaHasta
     * @param login
     * @param setId
     * @param bulkId
     * @return
     *     returns cl.blueprintsit.ws.bulkPreingreso.ArrayOfMovtoBajaBo
     */
    @WebMethod(operationName = "InfoSetBajas", action = "http://preingreso.metlife.cl/InfoSetBajas")
    @WebResult(name = "InfoSetBajasResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "InfoSetBajas", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.InfoSetBajas")
    @ResponseWrapper(localName = "InfoSetBajasResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.InfoSetBajasResponse")
    public ArrayOfMovtoBajaBo infoSetBajas(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        Integer bulkId,
        @WebParam(name = "setId", targetNamespace = "http://preingreso.metlife.cl/")
        Integer setId,
        @WebParam(name = "lote", targetNamespace = "http://preingreso.metlife.cl/")
        String lote,
        @WebParam(name = "fechaDesde", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaHasta,
        @WebParam(name = "corredorRutDv", targetNamespace = "http://preingreso.metlife.cl/")
        String corredorRutDv,
        @WebParam(name = "login", targetNamespace = "http://preingreso.metlife.cl/")
        String login);

    /**
     * 
     * @param fileNetCodigoGrabarResult
     * @param titularRut
     * @param grupo
     * @param polizaNumero
     * @param cargaRut
     * @param sesionId
     * @param errorNumero
     * @param errorDescripcion
     * @param titularDv
     * @param cargaDv
     * @param codigoFileNet
     * @param bulkId
     */
    @WebMethod(operationName = "FileNetCodigoGrabar", action = "http://preingreso.metlife.cl/FileNetCodigoGrabar")
    @RequestWrapper(localName = "FileNetCodigoGrabar", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.FileNetCodigoGrabar")
    @ResponseWrapper(localName = "FileNetCodigoGrabarResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.FileNetCodigoGrabarResponse")
    public void fileNetCodigoGrabar(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        int bulkId,
        @WebParam(name = "polizaNumero", targetNamespace = "http://preingreso.metlife.cl/")
        int polizaNumero,
        @WebParam(name = "grupo", targetNamespace = "http://preingreso.metlife.cl/")
        int grupo,
        @WebParam(name = "titularRut", targetNamespace = "http://preingreso.metlife.cl/")
        int titularRut,
        @WebParam(name = "titularDv", targetNamespace = "http://preingreso.metlife.cl/")
        int titularDv,
        @WebParam(name = "cargaRut", targetNamespace = "http://preingreso.metlife.cl/")
        Integer cargaRut,
        @WebParam(name = "cargaDv", targetNamespace = "http://preingreso.metlife.cl/")
        Integer cargaDv,
        @WebParam(name = "codigoFileNet", targetNamespace = "http://preingreso.metlife.cl/")
        String codigoFileNet,
        @WebParam(name = "errorNumero", targetNamespace = "http://preingreso.metlife.cl/", mode = WebParam.Mode.INOUT)
        Holder<Integer> errorNumero,
        @WebParam(name = "errorDescripcion", targetNamespace = "http://preingreso.metlife.cl/", mode = WebParam.Mode.INOUT)
        Holder<String> errorDescripcion,
        @WebParam(name = "FileNetCodigoGrabarResult", targetNamespace = "http://preingreso.metlife.cl/", mode = WebParam.Mode.OUT)
        Holder<ErrorBo> fileNetCodigoGrabarResult);

    /**
     * 
     * @param fechaDesde
     * @param sesionId
     * @param fechaHasta
     * @param bulkId
     * @return
     *     returns cl.blueprintsit.ws.bulkPreingreso.BulkDetalleBo
     */
    @WebMethod(operationName = "BulkDetalle", action = "http://preingreso.metlife.cl/BulkDetalle")
    @WebResult(name = "BulkDetalleResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "BulkDetalle", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.BulkDetalle")
    @ResponseWrapper(localName = "BulkDetalleResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.blueprintsit.ws.bulkPreingreso.BulkDetalleResponse")
    public BulkDetalleBo bulkDetalle(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "bulkId", targetNamespace = "http://preingreso.metlife.cl/")
        Integer bulkId,
        @WebParam(name = "fechaDesde", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaHasta);

}
