
package cl.blueprintsit.ws.bulkPreingreso;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.Properties;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "WsBulk", targetNamespace = "http://preingreso.metlife.cl/", wsdlLocation = "http://10.77.208.46:8080/wspreweb/WsBulk.asmx?wsdl")
public class WsBulk
        extends Service
{

    private final static URL WSBULK_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.blueprintsit.ws.bulkPreingreso.WsBulk.class.getName());

    static {
        Properties prop = new Properties();
        InputStream input = null;
        String urlString="";
        try {
            input = new FileInputStream("config.properties");
            // load a properties file
            prop.load(input);
            urlString=prop.getProperty("WsBulk");
            System.out.println("WsBulk WsBulk="+urlString);
        } catch(Exception e){
            System.out.println("WsBulk.static No se encuentra configurado el servicio WsBulk");
        }
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.blueprintsit.ws.bulkPreingreso.WsBulk.class.getResource(".");
            //url = new URL(baseUrl, "http://10.77.208.46:8080/wspreweb/WsBulk.asmx?wsdl");
            url = new URL(baseUrl, urlString+"?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '"+urlString+"?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSBULK_WSDL_LOCATION = url;
    }

    public WsBulk(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsBulk() {
        super(WSBULK_WSDL_LOCATION, new QName("http://preingreso.metlife.cl/", "WsBulk"));
    }

    /**
     *
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap")
    public WsBulkSoap getWsBulkSoap() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap"), WsBulkSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap")
    public WsBulkSoap getWsBulkSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap"), WsBulkSoap.class, features);
    }

    /**
     *
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap12")
    public WsBulkSoap getWsBulkSoap12() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap12"), WsBulkSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap12")
    public WsBulkSoap getWsBulkSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap12"), WsBulkSoap.class, features);
    }

}