
package cl.metlife.ws.clients.pipesponsor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SponsorModuleService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.77.208.158:8096/SponsorModuleService.svc?wsdl")
public class SponsorModuleService
    extends Service
{

    private final static URL SPONSORMODULESERVICE_WSDL_LOCATION;
    private final static WebServiceException SPONSORMODULESERVICE_EXCEPTION;
    private final static QName SPONSORMODULESERVICE_QNAME = new QName("http://tempuri.org/", "SponsorModuleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.77.208.158:8096/SponsorModuleService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SPONSORMODULESERVICE_WSDL_LOCATION = url;
        SPONSORMODULESERVICE_EXCEPTION = e;
    }

    public SponsorModuleService() {
        super(__getWsdlLocation(), SPONSORMODULESERVICE_QNAME);
    }

    public SponsorModuleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SPONSORMODULESERVICE_QNAME, features);
    }

    public SponsorModuleService(URL wsdlLocation) {
        super(wsdlLocation, SPONSORMODULESERVICE_QNAME);
    }

    public SponsorModuleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SPONSORMODULESERVICE_QNAME, features);
    }

    public SponsorModuleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SponsorModuleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISponsorMouleService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISponsorMouleService")
    public ISponsorMouleService getBasicHttpBindingISponsorMouleService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISponsorMouleService"), ISponsorMouleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISponsorMouleService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISponsorMouleService")
    public ISponsorMouleService getBasicHttpBindingISponsorMouleService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ISponsorMouleService"), ISponsorMouleService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPONSORMODULESERVICE_EXCEPTION!= null) {
            throw SPONSORMODULESERVICE_EXCEPTION;
        }
        return SPONSORMODULESERVICE_WSDL_LOCATION;
    }

}
