
package cl.metlife.ws.clients.preingreso.session;

import cl.metlife.abm.business.managers.ABMConfigurationManager;

import java.net.MalformedURLException;
import java.net.URL;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import javax.ejb.EJB;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class is generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2.
 *
 */
@WebServiceClient(name = "WsSesion", targetNamespace = "http://preingreso.metlife.cl/", wsdlLocation = "http://10.77.208.109:8085//WsSesion.asmx?wsdl")
public class WsSesion
        extends Service
{
    @EJB
    private ABMConfigurationManager configurationManager;
    private final static URL WSSESION_WSDL_LOCATION;
    private final static Logger logger = LogManager.getLogger(cl.metlife.ws.clients.preingreso.session.WsSesion.class);

    private final static WebServiceException WSSESION_EXCEPTION = null;
    private final static QName WSSESION_QNAME = new QName("http://preingreso.metlife.cl/", "WsSesion");

    static {
        URL url = null;
        URL baseUrl=null;
        try {

            baseUrl = WsSesion.class.getResource("WsSesion.asmx");
            System.out.println("session url:/"+baseUrl);
            url = new URL(baseUrl, "WsSesion.asmx");
        } catch (MalformedURLException e) {
            logger.warn("Failed to create URL for the wsdl Location: '"+baseUrl+"', retrying as a local file");
            logger.warn(e.getMessage());
        }
        WSSESION_WSDL_LOCATION = url;
    }

    public WsSesion() {
        super(__getWsdlLocation(), WSSESION_QNAME);
    }

    public WsSesion(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSESION_QNAME, features);
    }

    public WsSesion(URL wsdlLocation) {
        super(wsdlLocation, WSSESION_QNAME);
    }

    public WsSesion(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSESION_QNAME, features);
    }

    public WsSesion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSesion(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap")
    public WsSesionSoap getWsSesionSoap() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap"), WsSesionSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap")
    public WsSesionSoap getWsSesionSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap"), WsSesionSoap.class, features);
    }

    /**
     *
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap12")
    public WsSesionSoap getWsSesionSoap12() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap12"), WsSesionSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap12")
    public WsSesionSoap getWsSesionSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap12"), WsSesionSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSESION_EXCEPTION!= null) {
            throw WSSESION_EXCEPTION;
        }
        return WSSESION_WSDL_LOCATION;
    }

}
