
package cl.metlife.ws.clients.preingreso.session;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsSesionSoap", targetNamespace = "http://preingreso.metlife.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsSesionSoap {


    /**
     * 
     * @param login
     * @param pwd
     * @return
     *     returns cl.metlife.ws.clients.preingreso.session.SesionBo
     */
    @WebMethod(operationName = "Logon", action = "http://preingreso.metlife.cl/Logon")
    @WebResult(name = "LogonResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "Logon", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.session.Logon")
    @ResponseWrapper(localName = "LogonResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.session.LogonResponse")
    public SesionBo logon(
        @WebParam(name = "login", targetNamespace = "http://preingreso.metlife.cl/")
        String login,
        @WebParam(name = "pwd", targetNamespace = "http://preingreso.metlife.cl/")
        String pwd);

    /**
     * 
     * @param sesionId
     * @return
     *     returns cl.metlife.ws.clients.preingreso.session.ErrorBo
     */
    @WebMethod(operationName = "Logout", action = "http://preingreso.metlife.cl/Logout")
    @WebResult(name = "LogoutResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.session.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.session.LogoutResponse")
    public ErrorBo logout(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId);

    /**
     * 
     * @param sesionId
     * @return
     *     returns cl.metlife.ws.clients.preingreso.session.SesionBo
     */
    @WebMethod(operationName = "EvaluarSesion", action = "http://preingreso.metlife.cl/EvaluarSesion")
    @WebResult(name = "EvaluarSesionResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "EvaluarSesion", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.session.EvaluarSesion")
    @ResponseWrapper(localName = "EvaluarSesionResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.session.EvaluarSesionResponse")
    public SesionBo evaluarSesion(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId);

    /**
     * 
     * @param fechaHasta
     * @param fechaDesde
     * @param sesionId
     * @param login
     * @return
     *     returns cl.metlife.ws.clients.preingreso.session.LogBo
     */
    @WebMethod(operationName = "Log", action = "http://preingreso.metlife.cl/Log")
    @WebResult(name = "LogResult", targetNamespace = "http://preingreso.metlife.cl/")
    @RequestWrapper(localName = "Log", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.session.Log")
    @ResponseWrapper(localName = "LogResponse", targetNamespace = "http://preingreso.metlife.cl/", className = "cl.metlife.ws.clients.preingreso.session.LogResponse")
    public LogBo log(
        @WebParam(name = "sesionId", targetNamespace = "http://preingreso.metlife.cl/")
        String sesionId,
        @WebParam(name = "login", targetNamespace = "http://preingreso.metlife.cl/")
        String login,
        @WebParam(name = "fechaDesde", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "http://preingreso.metlife.cl/")
        XMLGregorianCalendar fechaHasta);

}
