
package cl.blueprintsit.ws.sesionPreingreso;

import org.apache.log4j.Level;
import org.slf4j.LoggerFactory;

import java.io.FileInputStream;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "WsSesion", targetNamespace = "http://preingreso.metlife.cl/", wsdlLocation = "http://10.77.208.46:8080/wspreweb/WsSesion.asmx?wsdl")
public class WsSesion
        extends Service
{

    private final static URL WSSESION_WSDL_LOCATION;
    private static final org.slf4j.Logger logger = LoggerFactory.getLogger(cl.blueprintsit.ws.sesionPreingreso.WsSesion.class.getName());

    static {
        Properties prop = new Properties();
        InputStream input = null;
        String urlString="";
        try {
            input = new FileInputStream("config.properties");
            // load a properties file
            prop.load(input);
            urlString=prop.getProperty("WsSesion");
            System.out.println("WsSesion WsSesion="+urlString);
        } catch(Exception e){
            System.out.println("WsSesion.static No se encuentra configurado el servicio WsSesion");
        }
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.blueprintsit.ws.sesionPreingreso.WsSesion.class.getResource(".");
            System.out.println("base: url 48 session preingreso"+baseUrl);
            //url = new URL(baseUrl, "http://10.77.208.46:8080/wspreweb/WsSesion.asmx?wsdl");
            url = new URL(baseUrl, urlString+"?wsdl");
        } catch (MalformedURLException e) {
            logger.warn("Failed to create URL for the wsdl Location: '"+urlString+"?wsdl', retrying as a local file");
            logger.warn(e.getMessage(),e);
        }
        WSSESION_WSDL_LOCATION = url;
    }

    public WsSesion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsSesion() {
        super(WSSESION_WSDL_LOCATION, new QName("http://preingreso.metlife.cl/", "WsSesion"));
    }

    /**
     *
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap")
    public WsSesionSoap getWsSesionSoap() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap"), WsSesionSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap")
    public WsSesionSoap getWsSesionSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap"), WsSesionSoap.class, features);
    }

    /**
     *
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap12")
    public WsSesionSoap getWsSesionSoap12() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap12"), WsSesionSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsSesionSoap
     */
    @WebEndpoint(name = "WsSesionSoap12")
    public WsSesionSoap getWsSesionSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsSesionSoap12"), WsSesionSoap.class, features);
    }

}