
package cl.metlife.ws.clients.preingreso.bulk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsBulk", targetNamespace = "http://preingreso.metlife.cl/", wsdlLocation = "http://10.77.208.109:8085/WsBulk.asmx?wsdl")
public class WsBulk
    extends Service
{

    private final static URL WSBULK_WSDL_LOCATION;
    private final static WebServiceException WSBULK_EXCEPTION;
    private final static QName WSBULK_QNAME = new QName("http://preingreso.metlife.cl/", "WsBulk");

    static {
        URL url = null;
        URL baseUrl=null;
        WebServiceException e = null;
        try {

            baseUrl =  WsBulk.class.getResource("WsBulk.asmx");
            System.out.println("baseurl bulk:"+baseUrl);
            url = new URL(baseUrl, "WsBulk.asmx");
        } catch (MalformedURLException ex) {
            System.out.println("Failed to create URL for the wsdl Location: '"+baseUrl+"', retrying as a local file");
            e = new WebServiceException(ex);

            System.out.println(e.getMessage());
        }
        WSBULK_EXCEPTION = e;
        WSBULK_WSDL_LOCATION = url;
    }

    public WsBulk() {
        super(__getWsdlLocation(), WSBULK_QNAME);
    }

    public WsBulk(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSBULK_QNAME, features);
    }

    public WsBulk(URL wsdlLocation) {
        super(wsdlLocation, WSBULK_QNAME);
    }

    public WsBulk(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSBULK_QNAME, features);
    }

    public WsBulk(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsBulk(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap")
    public WsBulkSoap getWsBulkSoap() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap"), WsBulkSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap")
    public WsBulkSoap getWsBulkSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap"), WsBulkSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap12")
    public WsBulkSoap getWsBulkSoap12() {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap12"), WsBulkSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsBulkSoap
     */
    @WebEndpoint(name = "WsBulkSoap12")
    public WsBulkSoap getWsBulkSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://preingreso.metlife.cl/", "WsBulkSoap12"), WsBulkSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSBULK_EXCEPTION!= null) {
            throw WSBULK_EXCEPTION;
        }
        return WSBULK_WSDL_LOCATION;
    }

}
