
package cl.blueprintsit.ws.filenet;

import org.slf4j.LoggerFactory;

import java.io.FileInputStream;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FileNetWS", targetNamespace = "http://filenet.ws.metlife.cl/", wsdlLocation = "http://mlfprdibmfnet.alico.corp:9080/WsFileNet/FileNetWS/FileNetWS.wsdl")
public class FileNetWS
    extends Service
{

    private static final URL FILENETWS_WSDL_LOCATION;
    private static final org.slf4j.Logger logger = LoggerFactory.getLogger(cl.blueprintsit.ws.filenet.FileNetWS.class.getName());

    static {
        Properties prop = new Properties();
        InputStream input = null;
        String urlString="";
        try {
            input = new FileInputStream("config.properties");
            // load a properties file
            prop.load(input);
            urlString=prop.getProperty("WsFileNet");
            System.out.println("FileNetWS WsFileNet="+urlString);
        } catch(Exception e){
            System.out.println("FileNetWS.static() No se encuentra configurado el servicio WsFileNet");
        }
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.blueprintsit.ws.filenet.FileNetWS.class.getResource(".");

            url = new URL(baseUrl, urlString+"?wsdl");
        } catch (MalformedURLException e) {
            logger.warn("Failed to create URL for the wsdl Location: '"+urlString+"?wsdl', retrying as a local file");
            logger.warn(e.getMessage(),e);
        }
        FILENETWS_WSDL_LOCATION = url;
    }

    public FileNetWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileNetWS() {

        super(FILENETWS_WSDL_LOCATION, new QName("http://filenet.ws.metlife.cl/", "FileNetWS"));
    }

    /**
     * 
     * @return
     *     returns ConectorFileNetWSI
     */
    @WebEndpoint(name = "Filenet")
    public ConectorFileNetWSI getFilenet() {
        return super.getPort(new QName("http://filenet.ws.metlife.cl/", "Filenet"), ConectorFileNetWSI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConectorFileNetWSI
     */
    @WebEndpoint(name = "Filenet")
    public ConectorFileNetWSI getFilenet(WebServiceFeature... features) {
        return super.getPort(new QName("http://filenet.ws.metlife.cl/", "Filenet"), ConectorFileNetWSI.class, features);
    }

}
