
package com.informatica.wsh;

import java.io.FileInputStream;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DataIntegrationService", targetNamespace = "http://www.informatica.com/wsh", wsdlLocation = "http://mlfpwcdev01.alico.corp:7333/wsh/services/BatchServices/DataIntegration?wsdl")
public class DataIntegrationService
    extends Service
{

    private final static URL DATAINTEGRATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.informatica.wsh.DataIntegrationService.class.getName());

    static {
        Properties prop = new Properties();
        InputStream input = null;
        String urlString="";
        try {
            input = new FileInputStream("config.properties");
            // load a properties file
            prop.load(input);
            urlString=prop.getProperty("WsDataIntegration");
            System.out.println("DataIntegrationService WsDataIntegration="+urlString);
        } catch(Exception e){
            System.out.println("DataIntegrationService.static() No se encuentra configurado el servicio de autentificacion");
        }

        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.informatica.wsh.DataIntegrationService.class.getResource(".");
            //url = new URL(baseUrl, "http://mlfpwcdev01.alico.corp:7333/wsh/services/BatchServices/DataIntegration?wsdl");
            url = new URL(baseUrl, urlString+"?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '"+urlString+"?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATAINTEGRATIONSERVICE_WSDL_LOCATION = url;
    }

    public DataIntegrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataIntegrationService() {
        super(DATAINTEGRATIONSERVICE_WSDL_LOCATION, new QName("http://www.informatica.com/wsh", "DataIntegrationService"));
    }

    /**
     * 
     * @return
     *     returns DataIntegrationInterface
     */
    @WebEndpoint(name = "DataIntegration")
    public DataIntegrationInterface getDataIntegration() {
        return super.getPort(new QName("http://www.informatica.com/wsh", "DataIntegration"), DataIntegrationInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataIntegrationInterface
     */
    @WebEndpoint(name = "DataIntegration")
    public DataIntegrationInterface getDataIntegration(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.informatica.com/wsh", "DataIntegration"), DataIntegrationInterface.class, features);
    }

}
