
package com.informatica.wsh;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "WSHFaultDetails", targetNamespace = "http://www.informatica.com/wsh")
public class Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultDetails faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Fault(String message, FaultDetails faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Fault(String message, FaultDetails faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.informatica.wsh.FaultDetails
     */
    public FaultDetails getFaultInfo() {
        return faultInfo;
    }

}
