package cl.metlife.ws.clients.filenet;
import java.net.MalformedURLException;
import java.net.URL;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "FileNetWS", targetNamespace = "http://filenet.ws.metlife.cl/", wsdlLocation = "http://mlfprdibmfnet.alico.corp:9080/WsFileNet/FileNetWS/FileNetWS.wsdl")
public class FileNetWS
        extends Service
{


    private final static Logger logger = LogManager.getLogger(cl.metlife.ws.clients.filenet.FileNetWS.class);



    public FileNetWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }



    /**
     *
     * @return
     *     returns ConectorFileNetWSI
     */
    @WebEndpoint(name = "Filenet")
    public ConectorFileNetWSI getFilenet() {
        return super.getPort(new QName("http://filenet.ws.metlife.cl/2/", "Filenet"), ConectorFileNetWSI.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConectorFileNetWSI
     */
    @WebEndpoint(name = "Filenet")
    public ConectorFileNetWSI getFilenet(WebServiceFeature... features) {
        return super.getPort(new QName("http://filenet.ws.metlife.cl/", "Filenet"), ConectorFileNetWSI.class, features);
    }

}
