
package cl.blueprintsit.business.authentication.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * [devuelve un xmldocument]
     * 
     * @param idAplicacion
     * @param clave
     * @param login
     * @return
     *     returns cl.blueprintsit.business.authentication.auth.AutentificaInternoResponse.AutentificaInternoResult
     */
    @WebMethod(operationName = "Autentifica_Interno", action = "http://tempuri.org/Autentifica_Interno")
    @WebResult(name = "Autentifica_InternoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Autentifica_Interno", targetNamespace = "http://tempuri.org/", className = "cl.blueprintsit.business.authentication.auth.AutentificaInterno")
    @ResponseWrapper(localName = "Autentifica_InternoResponse", targetNamespace = "http://tempuri.org/", className = "cl.blueprintsit.business.authentication.auth.AutentificaInternoResponse")
    public cl.blueprintsit.business.authentication.auth.AutentificaInternoResponse.AutentificaInternoResult autentificaInterno(
            @WebParam(name = "ID_Aplicacion", targetNamespace = "http://tempuri.org/")
                    String idAplicacion,
            @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
                    String login,
            @WebParam(name = "Clave", targetNamespace = "http://tempuri.org/")
                    String clave);

    /**
     * [devuelve un xmldocument]
     *
     * @param idAplicacion
     * @param login
     * @return
     *     returns cl.blueprintsit.business.authentication.auth.ROLESPERSONARUTAPLICResponse.ROLESPERSONARUTAPLICResult
     */
    @WebMethod(operationName = "ROLES_PERSONA_RUT_APLIC", action = "http://tempuri.org/ROLES_PERSONA_RUT_APLIC")
    @WebResult(name = "ROLES_PERSONA_RUT_APLICResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ROLES_PERSONA_RUT_APLIC", targetNamespace = "http://tempuri.org/", className = "cl.blueprintsit.business.authentication.auth.ROLESPERSONARUTAPLIC")
    @ResponseWrapper(localName = "ROLES_PERSONA_RUT_APLICResponse", targetNamespace = "http://tempuri.org/", className = "cl.blueprintsit.business.authentication.auth.ROLESPERSONARUTAPLICResponse")
    public cl.blueprintsit.business.authentication.auth.ROLESPERSONARUTAPLICResponse.ROLESPERSONARUTAPLICResult rolesPERSONARUTAPLIC(
            @WebParam(name = "ID_Aplicacion", targetNamespace = "http://tempuri.org/")
                    String idAplicacion,
            @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
                    String login);

    /**
     * [devuelve un String]
     *
     * @param clave
     * @param vlLogin
     * @return
     *     returns cl.blueprintsit.business.authentication.auth.LOGINResponse.LOGINResult
     */
    @WebMethod(operationName = "LOGIN", action = "http://tempuri.org/LOGIN")
    @WebResult(name = "LOGINResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LOGIN", targetNamespace = "http://tempuri.org/", className = "cl.blueprintsit.business.authentication.auth.LOGIN")
    @ResponseWrapper(localName = "LOGINResponse", targetNamespace = "http://tempuri.org/", className = "cl.blueprintsit.business.authentication.auth.LOGINResponse")
    public cl.blueprintsit.business.authentication.auth.LOGINResponse.LOGINResult login(
            @WebParam(name = "vl_login", targetNamespace = "http://tempuri.org/")
                    String vlLogin,
            @WebParam(name = "clave", targetNamespace = "http://tempuri.org/")
                    String clave);

    /**
     * [devuelve un String]
     *
     * @param inrut
     * @param icsession
     * @param icidioma
     * @param icclave
     * @return
     *     returns cl.blueprintsit.business.authentication.auth.CheckClaveResponse.CheckClaveResult
     */
    @WebMethod(operationName = "check_clave", action = "http://tempuri.org/check_clave")
    @WebResult(name = "check_claveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "check_clave", targetNamespace = "http://tempuri.org/", className = "cl.blueprintsit.business.authentication.auth.CheckClave")
    @ResponseWrapper(localName = "check_claveResponse", targetNamespace = "http://tempuri.org/", className = "cl.blueprintsit.business.authentication.auth.CheckClaveResponse")
    public cl.blueprintsit.business.authentication.auth.CheckClaveResponse.CheckClaveResult checkClave(
            @WebParam(name = "inrut", targetNamespace = "http://tempuri.org/")
                    String inrut,
            @WebParam(name = "icclave", targetNamespace = "http://tempuri.org/")
                    String icclave,
            @WebParam(name = "icsession", targetNamespace = "http://tempuri.org/")
                    String icsession,
            @WebParam(name = "icidioma", targetNamespace = "http://tempuri.org/")
                    String icidioma);

    /**
     * [Datos persona]
     *
     * @param inrut
     * @return
     *     returns cl.blueprintsit.business.authentication.auth.SpInfoPersonaResponse.SpInfoPersonaResult
     */
    @WebMethod(operationName = "sp_info_persona", action = "http://tempuri.org/sp_info_persona")
    @WebResult(name = "sp_info_personaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "sp_info_persona", targetNamespace = "http://tempuri.org/", className = "cl.blueprintsit.business.authentication.auth.SpInfoPersona")
    @ResponseWrapper(localName = "sp_info_personaResponse", targetNamespace = "http://tempuri.org/", className = "cl.blueprintsit.business.authentication.auth.SpInfoPersonaResponse")
    public cl.blueprintsit.business.authentication.auth.SpInfoPersonaResponse.SpInfoPersonaResult spInfoPersona(
            @WebParam(name = "inrut", targetNamespace = "http://tempuri.org/")
                    String inrut);

}
