
package cl.blueprintsit.business.authentication.auth;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.Properties;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://mlclwsqa02.alico.corp:302/WS_AUTENTIFICA.asmx?WSDL")
public class Service
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE_EXCEPTION;
    private final static QName SERVICE_QNAME = new QName("http://tempuri.org/", "Service");

    static {

        Properties prop = new Properties();
        InputStream input = null;
        String urlString="";
        try {
            input = new FileInputStream("config.properties");
            // load a properties file
            prop.load(input);
            urlString=prop.getProperty("AuthService");
            System.out.println("Service AuthService="+urlString);
        } catch(Exception e){
            System.out.println("Service.static() No se encuentra configurado el servicio de autentificacion");
        }

        URL url = null;
        WebServiceException e = null;
        try {
            URL baseUrl = Service.class.getResource("");
            url = new URL(baseUrl, urlString+"?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE_WSDL_LOCATION = url;
        SERVICE_EXCEPTION = e;
    }

    public Service() {
        super(__getWsdlLocation(), SERVICE_QNAME);
    }


    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE_QNAME);
    }


    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ServiceSoap"), ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ServiceSoap"), ServiceSoap.class, features);
    }

    /**
     *
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap12")
    public ServiceSoap getServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "ServiceSoap12"), ServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap12")
    public ServiceSoap getServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ServiceSoap12"), ServiceSoap.class, features);
    }

    /**
     *
     * @return
     *     returns ServiceHttpGet
     */
    @WebEndpoint(name = "ServiceHttpGet")
    public ServiceHttpGet getServiceHttpGet() {
        return super.getPort(new QName("http://tempuri.org/", "ServiceHttpGet"), ServiceHttpGet.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceHttpGet
     */
    @WebEndpoint(name = "ServiceHttpGet")
    public ServiceHttpGet getServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ServiceHttpGet"), ServiceHttpGet.class, features);
    }

    /**
     *
     * @return
     *     returns ServiceHttpPost
     */
    @WebEndpoint(name = "ServiceHttpPost")
    public ServiceHttpPost getServiceHttpPost() {
        return super.getPort(new QName("http://tempuri.org/", "ServiceHttpPost"), ServiceHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceHttpPost
     */
    @WebEndpoint(name = "ServiceHttpPost")
    public ServiceHttpPost getServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ServiceHttpPost"), ServiceHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE_EXCEPTION!= null) {
            throw SERVICE_EXCEPTION;
        }
        return SERVICE_WSDL_LOCATION;
    }

}
