
package cl.blueprintsit.business.authentication.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceHttpPost {


    /**
     * [devuelve un xmldocument]
     * 
     * @param idAplicacion
     * @param clave
     * @param login
     */
    @WebMethod(operationName = "Autentifica_Interno")
    public void autentificaInterno(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ID_Aplicacion")
                    String idAplicacion,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Login")
                    String login,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Clave")
                    String clave);

    /**
     * [devuelve un xmldocument]
     *
     * @param idAplicacion
     * @param login
     */
    @WebMethod(operationName = "ROLES_PERSONA_RUT_APLIC")
    public void rolesPERSONARUTAPLIC(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ID_Aplicacion")
                    String idAplicacion,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Login")
                    String login);

    /**
     * [devuelve un String]
     *
     * @param clave
     * @param vlLogin
     */
    @WebMethod(operationName = "LOGIN")
    public void login(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "vl_login")
                    String vlLogin,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "clave")
                    String clave);

    /**
     * [devuelve un String]
     *
     * @param inrut
     * @param icsession
     * @param icidioma
     * @param icclave
     */
    @WebMethod(operationName = "check_clave")
    public void checkClave(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "inrut")
                    String inrut,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "icclave")
                    String icclave,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "icsession")
                    String icsession,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "icidioma")
                    String icidioma);

    /**
     * [Datos persona]
     *
     * @param inrut
     * @return
     *     returns cl.blueprintsit.business.authentication.auth.DataSet
     */
    @WebMethod(operationName = "sp_info_persona")
    @WebResult(name = "DataSet", targetNamespace = "http://tempuri.org/", partName = "Body")
    public DataSet spInfoPersona(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "inrut")
                    String inrut);

}
